/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Temperatura;

import javax.swing.JOptionPane;
import org.example.Principio;

/**
 *
 * @author Acost
 */
public class TemperaturaGrafica extends javax.swing.JFrame {

    /**
     * Creates new form TemperaturaGrafica
     */
    public TemperaturaGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTemperatura = new javax.swing.JPanel();
        SelectorTem = new javax.swing.JComboBox<>();
        Valor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ValorTotal1 = new javax.swing.JTextField();
        Convertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AtrasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectorTem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Grados Celsius a Grados Fahrenheit", "2.Grados Fahrenheit a Grados Celsius", "3.Kelvin a Grados Celsius", "4.Grados Celsius a Kelvin", "5.Kelvin a Grados Fahrenheit", "6.Grados Fahrenheit a Kelvin" }));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese el valor a Convertir ");

        ValorTotal1.setEditable(false);

        Convertir.setText("Convertir");
        Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Conversión de Temperaturas");

        AtrasButton.setBackground(new java.awt.Color(255, 0, 0));
        AtrasButton.setForeground(new java.awt.Color(255, 255, 255));
        AtrasButton.setText("X");
        AtrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTemperaturaLayout = new javax.swing.GroupLayout(PanelTemperatura);
        PanelTemperatura.setLayout(PanelTemperaturaLayout);
        PanelTemperaturaLayout.setHorizontalGroup(
            PanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTemperaturaLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(SelectorTem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelTemperaturaLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTemperaturaLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addGroup(PanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTemperaturaLayout.createSequentialGroup()
                        .addComponent(Convertir)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTemperaturaLayout.createSequentialGroup()
                        .addGroup(PanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(179, 179, 179))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTemperaturaLayout.createSequentialGroup()
                .addComponent(AtrasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(62, 62, 62))
        );
        PanelTemperaturaLayout.setVerticalGroup(
            PanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTemperaturaLayout.createSequentialGroup()
                .addGroup(PanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTemperaturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(AtrasButton))
                .addGap(26, 26, 26)
                .addComponent(SelectorTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Convertir)
                .addGap(30, 30, 30)
                .addComponent(ValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirActionPerformed
        // TODO add your handling code here:
        SeleccionTemperatura temperatura = new SeleccionTemperatura();
        String selector;
        double valorTotal;
        
        selector = SelectorTem.getSelectedItem().toString();
        temperatura.Seleccion = selector;
        
        
        try{
            valorTotal = Double.parseDouble(Valor.getText());
            double total = temperatura.Eleccion(valorTotal);

            ValorTotal1.setText(String.valueOf(total));
        }catch(Exception e){
                
            String validar = Valor.getText();
            if(validar.isEmpty()){
                JOptionPane.showMessageDialog(null, "Por favor ingrese un valor valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        
    }//GEN-LAST:event_ConvertirActionPerformed

    private void AtrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasButtonActionPerformed
        // TODO add your handling code here:
        Principio atras = new Principio();
        
        PanelTemperatura.revalidate();
        PanelTemperatura.repaint();
        PanelTemperatura.removeAll();
        atras.setVisible(true);
    }//GEN-LAST:event_AtrasButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasButton;
    private javax.swing.JButton Convertir;
    public javax.swing.JPanel PanelTemperatura;
    private javax.swing.JComboBox<String> SelectorTem;
    private javax.swing.JTextField Valor;
    private javax.swing.JTextField ValorTotal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
