/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Divisas;

import javax.swing.JOptionPane;
import org.example.Principio;

/**
 *
 * @author Acost
 */
public class ConvertorDivisas extends javax.swing.JFrame {

    /**
     * Creates new form ConvertorDivisas
     */
    public ConvertorDivisas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelDivisas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SelectorDivisas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Valor = new javax.swing.JTextField();
        ConvertirBoton = new javax.swing.JButton();
        Resultado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Convertirdor de Divisas");

        SelectorDivisas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Peso Colombiano a Dollar", "2.Peso Colombiano a Euro", "3.Peso Colombiano a Libra Esterlina", "4.Peso Colombiano a Yen Japones", "5.Peso Colombiano a Won Surcoreano", "6.Dollar a Peso Colombiano ", "7.Euro a Peso Colombiano", "8.Libra Esterlina a Peso Colombiano", "9.Yen Japones a Peso Colombiano", "10. Won Surcoreano a Peso Colombiano" }));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Cantidad a Convertir");

        ConvertirBoton.setText("Convertir");
        ConvertirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirBotonActionPerformed(evt);
            }
        });

        Resultado.setEditable(false);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDivisasLayout = new javax.swing.GroupLayout(PanelDivisas);
        PanelDivisas.setLayout(PanelDivisasLayout);
        PanelDivisasLayout.setHorizontalGroup(
            PanelDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDivisasLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(PanelDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDivisasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDivisasLayout.createSequentialGroup()
                        .addGroup(PanelDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(SelectorDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDivisasLayout.createSequentialGroup()
                        .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDivisasLayout.createSequentialGroup()
                        .addComponent(ConvertirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(PanelDivisasLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PanelDivisasLayout.setVerticalGroup(
            PanelDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDivisasLayout.createSequentialGroup()
                .addGroup(PanelDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDivisasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(SelectorDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConvertirBoton)
                .addGap(18, 18, 18)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDivisas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDivisas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirBotonActionPerformed
        // TODO add your handling code here:
        CasosDivisas caso = new CasosDivisas();
        double valorTotal; 
        String selector;
        
        selector = SelectorDivisas.getSelectedItem().toString();
        caso.SeleccionDivisa = selector;
        
        try{
            valorTotal = Double.parseDouble(Valor.getText());
            double total = caso.convertirMonedas(valorTotal);

            Resultado.setText(String.valueOf(total));
        }catch(Exception e){
            String validar = Valor.getText();
            if(validar.isEmpty()){
                JOptionPane.showMessageDialog(null, "Por favor ingrese un valor valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_ConvertirBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principio atras = new Principio();
        
        PanelDivisas.revalidate();
        PanelDivisas.repaint();
        PanelDivisas.removeAll();
        atras.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertirBoton;
    public javax.swing.JPanel PanelDivisas;
    private javax.swing.JTextField Resultado;
    private javax.swing.JComboBox<String> SelectorDivisas;
    private javax.swing.JTextField Valor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
